"""
api/routes/reports.py
----------------------
Report-retrieval REST endpoints.

Endpoints:
  GET /api/reports/{incident_id} — fetch the investigation report for an incident

Author  : Member 3 — Vercel Setup & API Skeleton
Phase   : 1 (stub) → Phase 3 (full implementation)
"""

from __future__ import annotations

import logging

from fastapi import APIRouter, HTTPException
from fastapi.responses import JSONResponse

logger = logging.getLogger(__name__)

router = APIRouter()


# ---------------------------------------------------------------------------
# GET /api/reports/{incident_id}
# ---------------------------------------------------------------------------


@router.get(
    "/reports/{incident_id}",
    summary="Get investigation report",
    description="Returns the auto-generated investigation report for a correlated incident.",
)
async def get_report(incident_id: str) -> JSONResponse:
    """
    Retrieve the investigation report generated by the Report Agent.

    Phase 1: Always returns 404 (Report Agent not yet implemented).
    Phase 3: Fetches the stored HTML/PDF report path or JSON payload from DB.
    """
    logger.info("GET /api/reports/%s", incident_id)
    # TODO (Phase 3): SELECT report_path FROM reports WHERE incident_id=...
    raise HTTPException(
        status_code=404,
        detail=f"No report found for incident '{incident_id}'. "
               "Reports are generated by the Report Agent in Phase 3.",
    )
